steps:
  - name: maven:3.3-jdk-8
    id: Test
    entrypoint: mvn
    args: [ 'test' ]

  - name: maven:3.3-jdk-8
    id: Build
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/heritage-419111/my-repository/heritage:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/git'
    id: Retrieve SSH key
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: Clone ENV repo
    args:
      - clone
      - '-b'
      - candidate
      - git@github.com:khefto/heritage.git
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cd heritage
        sed -i "s#europe-west1-docker.pkg.*#europe-west1-docker.pkg.dev/heritage-419111/my-repository/heritage:$SHORT_SHA#g" kubernetes.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \\
        cd heritage && \\
        git config --global user.email $(git log --format='%an <%ae>' -n 1 HEAD)
        git config --global user.name $(git log --format='%an <%ae>' -n 1 HEAD)
        git add kubernetes.yaml && \\
        git commit -m "Deploying image europe-west1-docker.pkg.dev/heritage-419111/my-repository/heritage:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository heritage
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \\
        git push origin candidate
    volumes:
      - name: 'ssh'
        path: /root/.ssh
availableSecrets:
  secretManager:
    - versionName: projects/451224987883/secrets/Github/versions/1
      env: 'SSH_KEY'